version: "3.9"
services:
  sj_ids_postgres_dev:
    image: "postgres:14"
    container_name: sj_ids_postgres_dev
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_pass
      - POSTGRES_DB=stackjudge
      - PGDATA=/data/postgres
    ports:
      - "54322:5432"
  
  sj_ids_postgres_dev_test:
    image: "postgres:14"
    container_name: sj_ids_postgres_dev_test
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_pass
      - POSTGRES_DB=stackjudge
      - PGDATA=/data/postgres
    ports:
      - "54323:5432"