name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -
      uses: actions/checkout@v3
    -
      name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=1.0" >> $GITHUB_ENV
    -
      name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    -
      name: File system info
      run: |
        echo "===========> github.workspace var: ${{ github.workspace }}"
        echo "===========> pwd:"
        pwd
        echo "===========> ls -hal:"
        ls -hal
        echo "===========> ls -hal ./IDS:"
        ls -hal ./IDS
    - 
      name: Restore dependencies
      run: cd IDS/StackjudgeIdentityServer && dotnet restore
    - 
      name: Build
      run: cd IDS/StackjudgeIdentityServer && dotnet build  --no-restore
    -
      name: Build docker image
      run: |
        cd IDS && docker build --tag stackjudge_identity_server:latest .
    -
      name: Save docker image
      run: |
        cd IDS && docker save -o ./../stackjudge_identity_server:${{ env.RELEASE_VERSION }}.docker stackjudge_identity_server:latest
    -
      name: File system info
      run: |
        echo "===========> pwd:"
        pwd
        echo "===========> ls -hal:"
        ls -hal
        echo "===========> ls -hal ./IDS:"
        ls -hal ./IDS
    -
      name: Push do Cloudsmith
      uses: cloudsmith-io/action@2f8578217e6fa9fe305977bb278057514bccd8ea
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: push
        format: docker
        owner: stackjudge
        repo: stackjudge_identity_server
        republish: true
        file: ./stackjudge_identity_server:${{ env.RELEASE_VERSION }}.docker