name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    -
      uses: actions/checkout@v3
    - name: File system info
      run: |
        echo "===========> github.workspace var: ${{ github.workspace }}"
        echo "===========> pwd:"
        pwd
        echo "===========> ls -hal:"
    -
      name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - 
      name: Restore dependencies
      run: cd IDS\StackjudgeIdentityServer && dotnet restore
    - 
      name: Build
      run: cd IDS\StackjudgeIdentityServer && dotnet build  --no-restore
    - 
      name: Test
      run: dotnet test --no-build --verbosity normal
